server:
  port: 8080
spring:
  application:
    name: crediya-applications
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "crediya"
    schema: "public"
    username: "crediya"
    password: "crediya"
